### ISSUE TITLE
Week2 HW

### ISSUE THREAD

**Issue by gju06051** [bhkim003/SDS_B_18#14]
Week2 HW 결과물인 wavedorm, BlockIO 2가지 제출이 과제였는데 여기 계신 분들은 해당 파일 자체를 여기에 업로드해주세요.
Block IO와 같은 경우에는 blockIO에서 제공하는 확장자 폴더를 의미하는 것이고, 
Wavedorm과 같은 경우에는 .v든 .txt든 브라우저 상의 wavedorm사이트에 복붙해서 waveform을 띄울 수 있는 형식이면 상관없습니다.

**Comment by gju06051** [comment]
[BlockIO](https://app.diagrams.net/)
[Wavedorm](https://wavedrom.com/)

**Comment by bhkim003** [comment]
[Week_2_김병현.zip](https://github.com/bhkim003/SDS_B_18/files/9580279/Week_2_.zip)
