### ISSUE TITLE
HW4 리뷰 - BH

### ISSUE THREAD

**Issue by gju06051** [bhkim003/SDS_B_18#32]
일단 FIFO자체는 이해하신 것 같은데 전체 설계가 꼬인 것 같습니다. 
1) FIFO의 write enable과 read enable신호는 각각 write하는 모듈과 read하는 모듈에서 만들어져야 합니다. 
2) 여기서 각각 moduleA(counter), moduleB(accumulator)의 wr_en, rd_en을 만드는 logic에 FIFO의 empty와 full이 사용되는 것입니다. 

![image](https://user-images.githubusercontent.com/37738888/193703996-9b3d9fdc-9311-4c8b-aff8-c39397911c22.png)
예를 들어 FIFO에 write를 할 경우에 위와 같이 valid_i가 wr_en으로 사용되게 만드셨는데 그냥 valid만 write_en으로 사용하는 것이 아니라 (!full_o)을 같이 AND연산을 해준다던지 하여서 "full이 아니고 valid값일 때 write를 하여라"같은 logic을 설계해주는 식으로 해야 제대로 사용하는 것이라고 생각합니다. 

그리고 empty부분은 제가 잘 이해를 못하겠는데 설명 적어주시면 감사하겠습니다.

**Comment by bhkim003** [comment]
음.. 일단 empty_o는 empty_o == 0 && acc_go 일때 fifo와 acc에서 읽을 수 있도록 설계한 것입니다. 비어있을 때는 읽으면 안되게, 그리고 acc에서 누산되지 못하도록 처리하기 위함입니다. 그래서 acc의 valid_i에도 re_en에 들어갈 신호를 똑같이 넣어주었습니다. 실제 회로라면 타이밍 이슈가 있을 순 있지만 이 경우 러프하게 반 클락도 안 걸릴 경우를 가정하고 설계하였습니다.
 말씀하신대로 full_o를 써서 counter_go와 !full_o를 and로 묶어서 wr_en으로 넣어버리면 좋을 것 같습니다. 굳이 counter 의 valid_o와 묶지 않는 것은 사용자가 카운팅하기를 원하지 않을 때(counter_go가 0일 때)는 카운터가 돌아가지 않기를 바라기 때문입니다. 이런 관점에서 counter의 valid_o는 그냥 인터페이스에서 삭제시키고 counter의 en와 fifo의 wr_en 모두를 그냥  !full_o && counter_go로 처리하면 될 것 같습니다. 물론 타이밍 문제는 해결해야 할 것입니다. 
시간이 나면 수정해서 올리도록 하겠습니다.


추신.

혹시 1. 에서 말씀하신 점이 fifo의 wr_en, re_en이 순전히 top module의 사용자의 input없이 내부 모듈의 output으로만 만들기를 지향하시는 것인가요? 이해가 느린 점 죄송합니다.

**Comment by gju06051** [comment]
사실 뭐 너무 간단한 logic이라 설계방법이나 구조에 그렇게 관여하고싶지는 않은데 오늘 soc실습해보시면 어떤 느낌인지 아실거 같습니다. 수고하셨습니다.
